batch_size: 16
epoch: 200
learning_rate: 0.01
scheduler_step: 20
scheduler_gamma: 0.1

gpu: 1
num_workers : 16  # 数据处理进程数
num_point: 1024
optimizer: SGD
weight_decay: 1e-4

# else
normal: True
num_class: 40
input_dim: 6

defaults:
  - _self_
  - model: Hengshuang

hydra: 
  run:
    dir: log/${hydra.job.name}/${model.name}/${now:%m-%d_%H:%M:%S}

  sweep:
    dir: log/multirun_${hydra.job.name}/multirun${now:%m-%d_%H:%M}
    subdir: ${hydra.job.override_dirname}